# Project information
site_name: WAFER ML-OPS docs
# define TOC or order of website-
nav:
  - Home: index.md
  - Project: project.md
  - Pipeline Stage 1 (Initial setup): stage1_init_setup.md
  - Reference: reference.md

site_author: Sunny Bhaveen Chandra
site_description: >-
  DESCRIPTION

# Repository
repo_name: c17hawke/mlops_main
repo_url: https://github.com/c17hawke/mlops_main

extra_css:
  - stylesheets/extra.css

# Configuration
theme:
  name: material
  features:
    - tab
  language: en
  palette:
    scheme: slate
    primary: teal
    accent: teal

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/c17hawke
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/c17hawke
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/c17hawke
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/c17hawke/

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
markdown_extensions:
  - codehilite:
      linenums: false
  - admonition
  - pymdownx.arithmatex
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.highlight
  - attr_list

copyright: |
  &copy; 2021 <a href="https://github.com/c17hawke"  target="_blank" rel="noopener">Sunny Bhaveen Chandra</a>
